USE university_db;

ALTER TABLE College ADD FOREIGN KEY (Dean_Id) REFERENCES Instructor(Id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE Dept ADD FOREIGN KEY (Chair_Id) REFERENCES Instructor(Id) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE Dept ADD FOREIGN KEY (CName) REFERENCES College(CName) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE Instructor ADD FOREIGN KEY (DCode) REFERENCES Dept(DCode) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE Course ADD FOREIGN KEY (DCode) REFERENCES Dept(DCode) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE Student ADD FOREIGN KEY (DCode) REFERENCES Dept(DCode) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE Section ADD FOREIGN KEY (CCode) REFERENCES Course(CCode) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Section ADD FOREIGN KEY (Inst_Id) REFERENCES Instructor(Id) ON UPDATE CASCADE ON DELETE SET NULL;

ALTER TABLE Takes ADD FOREIGN KEY (SId) REFERENCES Student(SId) ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE Takes ADD FOREIGN KEY (Sec_Id) REFERENCES Section(Sec_Id) ON UPDATE CASCADE ON DELETE CASCADE;
